config/routes.rb
Rails.application.routes.draw do
  root to: 'main#index'
  #main controller
  get 'about', to: 'main#about'
  # recipe controller
  get 'breakfast', to: 'recipe#breakfast'
  get 'dinner', to: 'recipe#dinner'
  get 'recipes', to: 'recipe#index'
  get 'recipes/:id', to: 'recipe#show'
  get 'lunch', to: 'recipe#lunch'
  # authentication controller
  get 'register', to: 'auth#register'
  post 'register', to: 'auth#store_register'
  get 'login', to: 'auth#login'
  post 'login', to: 'auth#store_login'
  delete 'logout', to: 'logout#logout'
  # user recipe
  get '/users/recipe/create', to: 'user_recipe#create'
  get '/users/recipes/:id/edit', to: 'user_recipe#edit'
  post '/users/recipes/:id/edit', to: 'user_recipe#edit_recipe'
  post '/users/recipes/:id/delete', to: 'user_recipe#delete'
  get '/users/recipes', to: 'user_recipe#index'
  post '/users/recipe/create', to: 'user_recipe#store_recipe'
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def created_at
    attributes['created_at'].strftime("%Y-%m-%d %H:%M %Z")
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  VALID_NUMBER = /\d/i.freeze
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :name, presence: true
  validates :photo, presence: true
  validates :prep, presence: true,format: { with: VALID_NUMBER }
  validates :cook, presence: true, format: { with: VALID_NUMBER }
  validates :direction, presence: true
  validates :ingredient, presence: true
  validates :country, presence: true
  attribute :user_id
  attribute :category_id
  belongs_to :category
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false },allow_blank: false
  validates :name, presence: true
  validates :password, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  def set_current_user
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    redirect_to root_path, alert: 'You must signed in' if Current.user.nil?
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end

  def register
    @user = User.new
  end

  def store_login
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_recipes_path
    else
      flash.now[:alert] = 'Invalid email or password'
      render :login
    end

  end

  def store_register
    @user = User.new(register_params)
    if @user.save
      redirect_to root_path, notice: 'Account created, please check your email for the code'
    else
      render :register
    end
  end

  private
  def register_params
    params.permit(:name, :email, :password, :password_confirmation,)
  end
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  before_action :require_user_logged_in!
  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @recipes = Recipe.order('created_at').limit(4).preload(:user, :category)
  end

  def about
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    @recipes = Recipe.preload(:user, :category)
    puts(@recipes.inspect)
  end

  def lunch
    @recipes = Recipe.where(category_id: Integer(2)).preload(:user, :category)
    puts(@recipes.inspect)
  end

  def dinner
    @recipes = Recipe.where(category_id: Integer(1)).preload(:user, :category)
    puts(@recipes.inspect)
  end

  def breakfast
    @recipes = Recipe.where(category_id: Integer(3)).preload(:user, :category)
    puts(@recipes.inspect)
  end

  def show
    @id = params[:id]
    @recipe = Recipe.where(id: Integer(params[:id])).preload(:user, :category).first
    puts(@recipe.inspect)
  end
end

app/controllers/user_recipe_controller.rb
require 'aws-sdk-s3'

class UserRecipeController < ApplicationController
  before_action :require_user_logged_in!

  def index
    if session[:user_id]
      @recipes = Recipe.where(user_id: Integer(session[:user_id])).preload(:user, :category)
    end
  end

  def create
    @recipe = Recipe.new
    @categories = Category.all
    @data = RecipeCountry.get_countries
  end

  def store_recipe

    @recipe = Recipe.new(user_recipe_params)
    object_key = params[:photo].original_filename
    file = params[:photo].tempfile
    url = "https://my-cookbook-photos.s3.amazonaws.com/#{object_key}"
    upload_to_s3(file,object_key)
    @recipe.photo = url
    if @recipe.save
      redirect_to users_recipe_create_path, notice: 'Recipe created successfully'
    else
      @categories = Category.all
      @data= RecipeCountry.get_countries
      render :create
    end


  end

  def edit
    @categories = Category.all
    @id = params[:id]
    @recipe = Recipe.find(params[:id])
  end

  def edit_recipe
    recipe = params.permit(:name, :prep, :cook, :direction, :ingredient, :user_id, :category_id)
    @recipe = Recipe.find(params[:id]).update(recipe)
    if @recipe
      redirect_to users_recipes_path, notice: 'Recipe has been updated successfully'
    else
      @id = params[:id]
      @recipe = Recipe.find(params[:id])
      @categories = Category.all
      flash.now[:alert] = 'Something went wrong, please try again'
      render :edit
    end

  end

  def delete
    recipe = Recipe.delete(params[:id])
    if recipe
      redirect_to users_recipes_path, notice: 'Recipe has been deleted successfully'
    else
      redirect_to users_recipes_path, alert: 'Something went wrong'
    end
  end

  def show; end

  private

  def user_recipe_params
    params.permit(:name, :prep, :cook, :direction, :ingredient, :user_id, :category_id,:country)
  end

  def upload_to_s3(file,object_key)
    client = Aws::S3::Client.new(
      region: "us-east-1",
      credentials: Aws::Credentials.new("AKIA37R36ZD5YOP2477C", "EzVmSETmBT8XVRoiL8U0cAfPGtaVODqO2xINy4gw"),

      )
    begin
      return client.put_object(
        bucket: "my-cookbook-photos",
        key: object_key,
        body: file,
        )

    rescue StandardError => e
      puts "Error uploading object: #{e.message}"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My CookBook: All your recipes in one place.</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <%= favicon_link_tag asset_path('favicon.ico') %>
</head>

<body>

<%= render partial: "partials/nav" %>
<main>
  <div class="container">
      <div class="columns is-mobile">
        <div class="column">
          <%= render partial: "partials/flash" %>
        </div>
      </div>
  </div>
  <%= yield %>
</main>
<%= render partial: "partials/footer"%>
</body>
</html>

app/views/main/about.html.erb
about page

app/views/main/index.html.erb
<%= render partial: "partials/hero" %>
<%= render partial: "partials/recent" %>

app/views/partials/_flash.erb
<% if flash[:alert] %>
<div class="notification is-danger flash">
	<%=flash[:alert] %>
</div>
<%end %>
<% if flash[:notice] %>
<div class="notification is-alert flash">
	<%=flash[:notice] %>
</div>
<%end %>

app/views/partials/_footer.erb
<footer class="footer">
	<div class="has-text-centered">
			<strong>MyCookBookApp © 2022</strong> by <a href="#">Cristina Sias</a>. The source code is licensed
			<a href="#">MIT</a>. The website content
			is licensed <a href="#">CC BY NC SA 4.0</a>.
	</div>
</footer>

app/views/partials/_hero.erb
<div class="container-full">
  <%= image_tag('https://my-cookbook-photos.s3.amazonaws.com/platter-g01cf37a5c_1920.jpg') %>
</div>

app/views/partials/_nav.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <%= image_tag 'logo.png' %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "All Recipes" ,recipes_path ,class: "navbar-item" %>
      <%= link_to "Lunch" , lunch_path,class: "navbar-item" %>
      <%= link_to "Breakfast" ,breakfast_path ,class: "navbar-item" %>
      <%= link_to "Dinner" ,dinner_path ,class: "navbar-item" %>
      <% if Current.user %>
        <%= link_to "My recipes" ,users_recipes_path ,class: "navbar-item" %>
        <%= link_to "New Recipe" ,users_recipe_create_path ,class: "navbar-item" %>
      <%end %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if Current.user %>
            <span class="mr-1 ml-1">Hey,  <%= Current.user.name %></span>
            <div class="navbar-start">
              <%= button_to "Logout",logout_path,method: :delete,class: "button"%>
            </div>
          <%else %>
            <%= link_to "Sign up" ,register_path ,class: "button is-primary" %>
            <%= link_to "Log in" ,login_path ,class: "button is-light" %>
          <%end %>

        </div>
      </div>
    </div>
  </div>
</nav>

app/views/partials/_recent.erb
<div class="container">
  <p class="is-size-4 my-2">Most Recent Recipes</p>
  <div class="columns">
    <% @recipes.each do |recipe|%>
      <div class="column is-3">
        <div class="card recipe_card">
          <span class="tag is-dark category_label"><%=recipe.category.name %></span>
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="<%=recipe.photo %>" alt="Placeholder image">
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-5"><%=recipe.name %></p>
              <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>
                <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= recipe.user.name %>
              </span>
            </span>
              </div>
            </div>
            <a href="/recipes/<%= recipe.id %>">
              <button class="button is-black is-small">View Recipe ></button>
            </a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipe/breakfast.html.erb
<div class="container">
  <% if @recipes.size==0 %>
    <div class="notification is-info is-light">
      No Recipes available
    </div>
  <% else %>
    <div class="is-flex is-flex-wrap-wrap">
      <% @recipes.each do |recipe|%>
        <div class="column is-3">
          <div class="card recipe_card">
            <span class="tag is-dark category_label"><%=recipe.category.name %></span>
            <div class="card-image">
              <figure class="image is-4by3">
                <img src="<%=recipe.photo %>" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <p class="title is-5"><%=recipe.name %></p>
                <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>
                  <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= recipe.user.name %>
              </span>
            </span>
                </div>
              </div>
              <a href="/">
                <button class="button is-black is-small">View Recipe ></button>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipe/dinner.html.erb
<div class="container">
  <% if @recipes.size==0 %>
    <div class="notification is-info is-light">
      No Recipes available
    </div>
  <% else %>
    <div class="is-flex is-flex-wrap-wrap">
      <% @recipes.each do |recipe|%>
        <div class="column is-3">
          <div class="card recipe_card">
            <span class="tag is-dark category_label"><%=recipe.category.name %></span>
            <div class="card-image">
              <figure class="image is-4by3">
                <img src="<%=recipe.photo %>" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <p class="title is-5"><%=recipe.name %></p>
                <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>
                  <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= recipe.user.name %>
              </span>
            </span>
                </div>
              </div>
              <a href="/recipes/<%= recipe.id %>">
                <button class="button is-black is-small">View Recipe ></button>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipe/index.html.erb
<div class="container">
  <% if @recipes.size==0 %>
    <div class="notification is-info is-light">
      No Recipes available
    </div>
  <% else %>
  <div class="is-flex is-flex-wrap-wrap">
      <% @recipes.each do |recipe|%>
        <div class="column is-3">
          <div class="card recipe_card">
            <span class="tag is-dark category_label"><%=recipe.category.name %></span>
            <div class="card-image">
              <figure class="image is-4by3">
                <img src="<%=recipe.photo %>" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <p class="title is-5"><%=recipe.name %></p>
                <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>
                  <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= recipe.user.name %>
              </span>
            </span>
                </div>
              </div>
              <a href="/recipes/<%= recipe.id %>">
                <button class="button is-black is-small">View Recipe ></button>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipe/lunch.html.erb
<div class="container">
  <% if @recipes.size==0 %>
    <div class="notification is-info is-light">
      No Recipes available
    </div>
  <% else %>
    <div class="is-flex is-flex-wrap-wrap">
      <% @recipes.each do |recipe|%>
        <div class="column is-3">
          <div class="card recipe_card">
            <span class="tag is-dark category_label"><%=recipe.category.name %></span>
            <div class="card-image">
              <figure class="image is-4by3">
                <img src="<%=recipe.photo %>" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <p class="title is-5"><%=recipe.name %></p>
                <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>
                  <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= recipe.user.name %>
              </span>
            </span>
                </div>
              </div>
              <a href="/recipes/<%= recipe.id %>">
                <button class="button is-black is-small">View Recipe ></button>
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipe/show.html.erb
  <section class="is-relative section">
    <div class="container">
      <div class="columns is-multiline">
        <div class="column is-12 is-6-tablet is-5-desktop mb-0-desktop">
          <figure class="image is-4by3">
            <img src="<%=@recipe.photo %>" alt="Placeholder image">
          </figure>
          <div class="ingredient">
            <p class="mt-4">
              <span class="has-text-weight-semibold">
              Ingredients:
              </span><br>
              <%= @recipe.ingredient %>
            </p>
          </div>

        </div>
        <div class="column is-12 is-7-tablet is-7-desktop">
          <div class="has-mw-xl-desktop">
            <h4 class="mb-16 mb-24-desktop">Origin: <%=@recipe.country %></h4>
            <h2 class="mb-16 mb-24-desktop title is-2"><%=@recipe.name %></h2>
            <div class="content">
              <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                Prep:
                  <%=(@recipe.prep.to_i) %>  mins
              </span>
            </span>
                <span>
                 <span class="icon">
                     <i class="bi bi-clock"></i>
                 </span>
                <span class="is-size-7">
                  Cook:
                  <%=(@recipe.cook.to_i) %>  mins
                </span>
            </span>
                <span>
                 <span class="icon">
                     <i class="bi bi-clock"></i>
                 </span>
                <span class="is-size-7">
                  Ready In:
                  <%=(@recipe.cook.to_i + @recipe.prep.to_i) %>  mins
                </span>
            </span>
                <span>
               <span class="icon mx-0">
                   <i class="bi bi-person"></i>
               </span>
              <span class="is-size-7">
                   <%= @recipe.user.name %>
              </span>
            </span>
              </div>
            </div>
            <div class="instruction">
              <p><%= @recipe.direction %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/user_recipe/create.html.erb
<div class="container py-3 form__container">
  <div class="columns is-multiline is-mobile">
    <div class="column is-half is-offset-one-quarter">
      <h3 class="title is-3 has-text-centered is-capitalized ">New Recipies</h3>
      <hr class="mb-4">
      <div class="card">
        <div class="card-content">
          <div class="content">
            <% if @recipe.errors.any? %>
              <%@recipe.errors.full_messages.each do |message| %>
                <p  class="help is-danger my-1"><%= message %></p>
              <%end %>
            <%end %>
            <form action="/users/recipe/create" method="post"  enctype="multipart/form-data" >
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="hidden" name="user_id" value="<%= Current.user.id %>">
              <div class="field">
                <label class="label">Name</label>
                <p class="control">
                  <input class="input" type="text" placeholder="e.g. Pasta" name="name">
                </p>
              </div>

              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Category</label>
                    <div class="select is-fullwidth">
                      <select name="category_id">
                        <option selected disabled>Select</option>
                        <% @categories.each do |category| %>
                          <option value="<%=category[:id] %>" ><%= category[:name] %></option>
                        <% end %>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="column">
                  <div class="field w-100">
                    <label class="label">Photo</label>
                    <input type="file" name="photo" required>
                  </div>
                </div>
              </div>
              <div class="field">
                <label class="label">Country Of Origin</label>
                <div class="select is-fullwidth">
                  <select name="country">
                    <option selected disabled>Select</option>
                    <% @data.each do |country| %>
                      <option value="<%=country[:name] %>" ><%= country[:name] %></option>
                    <% end %>
                  </select>
                </div>
              </div>
              <div class="columns">
                <div class="column">
                  <div class="field">
                    <label class="label">Prep</label>
                    <p class="control">
                      <input class="input" type="text" placeholder="e.g. 30 min" name="prep">
                    </p>
                  </div>
                </div>
                <div class="column">
                  <div class="field">
                    <label class="label">Cook</label>
                    <p class="control">
                      <input class="input" type="text" placeholder="e.g. 20 min" name="cook">
                    </p>
                  </div>
                </div>
              </div>
              <div class="field">
                <label class="label">Ingredients</label>
                <p class="control">
                  <textarea class="textarea" placeholder="e.g. Cheese, Onions" rows="5" name="ingredient"></textarea>
                </p>
              </div>
              <div class="field">
                <label class="label">Direction</label>
                <p class="control">
                  <textarea class="textarea" placeholder="e.g. Add onion" rows="5" name="direction"></textarea>
                </p>
              </div>
              <div class="field">
                <p class="control">
                  <button class="button is-primary" type="submit">
                   Save
                  </button>
                </p>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/user_recipe/edit.html.erb
<div class="container">
  <div class="container py-3 form__container">
    <div class="columns is-multiline is-mobile">
      <div class="column is-half is-offset-one-quarter">
        <h3 class="title is-3 has-text-centered is-capitalized ">Edit Recipe</h3>
        <hr class="mb-4">
        <div class="card">
          <div class="card-content">
            <div class="content">
              <% if @recipe.errors.any? %>
                <%@recipe.errors.full_messages.each do |message| %>
                  <p  class="help is-danger my-1"><%= message %></p>
                <%end %>
              <%end %>
              <form action="/users/recipes/<%=@id%>/edit" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="user_id" value="<%= Current.user.id %>">
                <input type="hidden" name="car_id" value="<%= @id %>">
                <div class="field">
                  <label class="label">Name</label>
                  <p class="control">
                    <input class="input" value="<%=@recipe.name%>" type="text" placeholder="e.g. Pasta" name="name">
                  </p>
                </div>

                <div class="columns">
                  <div class="column">
                    <div class="field">
                      <label class="label">Category</label>
                      <div class="select is-fullwidth">
                        <select name="category_id">
                          <option selected disabled>Select</option>
                          <% @categories.each do |category| %>
                            <option value="<%=category[:id] %>" ><%= category[:name] %></option>
                          <% end %>
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="column">
                    <div class="field">
                      <label class="label">Photo</label>
                      <p class="control">
                        <input class="input" type="text"  value="<%=@recipe.prep%>" placeholder="e.g. Photo" name="photo">
                      </p>
                    </div>
                  </div>
                </div>

                <div class="columns">
                  <div class="column">
                    <div class="field">
                      <label class="label">Prep</label>
                      <p class="control">
                        <input class="input" value="<%=@recipe.prep%>" type="text" placeholder="e.g. 30 min" name="prep">
                      </p>
                    </div>
                  </div>
                  <div class="column">
                    <div class="field">
                      <label class="label">Cook</label>
                      <p class="control">
                        <input class="input" type="text" value="<%=@recipe.cook%>" placeholder="e.g. 20 min" name="cook">
                      </p>
                    </div>
                  </div>
                </div>
                <div class="field">
                  <label class="label">Ingredients</label>
                  <p class="control">
                    <textarea class="textarea"  placeholder="e.g. Cheese, Onions" rows="5" name="ingredient"><%=@recipe.ingredient%></textarea>
                  </p>
                </div>
                <div class="field">
                  <label class="label">Direction</label>
                  <p class="control">
                    <textarea class="textarea"  placeholder="e.g. Add onion" rows="5" name="direction"><%=@recipe.direction%></textarea>
                  </p>
                </div>
                <div class="field">
                  <p class="control">
                    <button class="button is-primary" type="submit">
                      Save
                    </button>
                  </p>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/user_recipe/index.html.erb
<div class="container">
  <% if @recipes.size==0 %>
    <div class="notification is-info is-light">
      No Recipes available
    </div>
  <% else %>
    <div class="is-flex is-flex-wrap-wrap">
      <% @recipes.each do |recipe|%>
        <div class="column is-3">
          <div class="card recipe_card">
            <span class="tag is-dark category_label"><%=recipe.category.name %></span>
            <div class="card-image">
              <figure class="image is-4by3">
                <img src="<%=recipe.photo %>" alt="Placeholder image">
              </figure>
            </div>
            <div class="card-content">
              <div class="content">
                <p class="title is-5"><%=recipe.name %></p>
                <div class="mt-0 is-flex-direction-row is-justify-content-space-between">
              <span>
               <span class="icon">
                   <i class="bi bi-clock"></i>
               </span>
              <span class="is-size-7">
                  <%=(recipe.cook.to_i + recipe.prep.to_i) %>  mins
              </span>
            </span>

                </div>
              </div>
              <div class="is-flex">
                <a href="/recipes/<%= recipe.id %>" class="ml-3">
                  <button class="button is-black is-small">View</button>
                </a>
                <a href="/users/recipes/<%= recipe.id %>/edit" class="ml-3">
                  <button class="button is-success is-small">Edit</button>
                </a>
                <form action="/users/recipes/<%= recipe.id %>/delete" method="post" class="is-hoverable ml-3">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="user_id" value="<%= Current.user.id %>">
                  <button class="button is-danger is-small">Delete</button>
                </form>
              </div>

            </div>
          </div>
        </div>
      <% end %>
  <% end %>
  </div>
</div>